//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pruebas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class venta
    {
        public venta()
        {
            this.venta_has_producto = new HashSet<venta_has_producto>();
        }
    
        public int id { get; set; }
        public string fecha { get; set; }
        public Nullable<decimal> total { get; set; }
    
        public virtual ICollection<venta_has_producto> venta_has_producto { get; set; }
    }
}
