//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pruebas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class venta_has_producto
    {
        public int Venta_id { get; set; }
        public int Producto_id { get; set; }
        public Nullable<decimal> precioVenta { get; set; }
    
        public virtual producto producto { get; set; }
        public virtual venta venta { get; set; }
    }
}
